name: Go File Explorer CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'  # Specify the Go version

    - name: Build the Go application
      run: |
        go build -v -o fileExplorer ./main.go

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: fileExplorer
        path: fileExplorer

    # Add deployment step here
    # Example: Deploy to a server using SSH
    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        source: "fileExplorer"
        # target: "/path/on/server/"

    # Any other deployment or notification steps can be added here
